# Dockerfile
FROM python:3.11.4


RUN apt-get update && apt-get install -y \
    ghostscript \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    lpr\
    libgl1 \
    libglib2.0-0 \
    libxkbcommon-x11-0 \
    libxcb-xinerama0 \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    libxcb1 \
    libxcb-render0 \
    libxcb-shape0 \
    libxcb-xfixes0 \
    libx11-xcb-dev \
    libfontconfig1 \
    libdbus-1-3 \
    libxi6 \
    libxcb-randr0 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-shm0 \
    libxrender1 \
    libxcb-icccm4 \
    libxcb-sync1 \
    libxcb-xkb1 \
    libxshmfence1 \
    libxxf86vm1 \
    libxcb-xinerama0 \
    xkb-data \
    libxcb-shape0 \
    libxcb-xfixes0 \
    libxcb-randr0 \
    libxcb-image0 \
    libxcb-keysyms1 \
    libxcb-shm0 \
    libxcb-render-util0 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade opencv-python-headless
RUN pip uninstall opencv-python
RUN pip install opencv-python==4.8.0.76
WORKDIR /app

# set ENV vars
#ENV QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/lib/python3.11/site-packages/cv2/qt/plugins
ENV QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/lib/python3.11/site-packages/PyQt5/Qt5/plugins
ENV QT_QPA_PLATFORM=xcb

COPY requirements.txt .
RUN pip install -r requirements.txt
COPY v1 /app/v1
COPY v2 /app/v2
COPY v3 /app/v3
COPY hello.py .
CMD ["python", "/app/v2/PrinterApp_v2/main.py"]
#CMD["python","/app/informatics_paper_v3/PrinerApp_v3/redcapLabelwriterApp_v3_mac.py"]


